---
public_folder: public
services:
    solve:
        evaluator: [python, services/play.py]
        args:
            board:
                regex: ^[1-9 ]+$
                default: "3 4 5"
                explain: array with each piles's height

    #synopsis:
    #    evaluator: [python, services/synopsis/synopsis_driver.py]
    #    args:
    #        service:
    #            regex: ^((\S)+)$
    #            default: synopsis
    #            explain: any string without space characters but meant to specify one of the services of the problem %(problem)s
    #        lang:
    #            regex: ^(hardcoded|hardcoded_ext|en|it)$
    #            default: it
    #        metafile:
    #            regex: ^(main|en|it)$
    #            default: main
...
